login: Dream Tata
password: eba512bde3
url_login: https://test-stand.gb.ru/gateway/login
url_posts: https://test-stand.gb.ru/api/posts
title: title_test_post
description: description_test_post
content: content_test_post